# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Dell 5490/zynq_axi_timer_led/zynq_axi_timer_led.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
# IP: The module: 'design_1_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Dell 5490/zynq_axi_timer_led/zynq_axi_timer_led.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/bd_afc3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Dell 5490/zynq_axi_timer_led/zynq_axi_timer_led.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/bd_afc3_sc_ul_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/Dell 5490/zynq_axi_timer_led/zynq_axi_timer_led.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/bd_afc3_sc_ul_0_cdc.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Dell 5490/zynq_axi_timer_led/zynq_axi_timer_led.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Dell 5490/zynq_axi_timer_led/zynq_axi_timer_led.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Dell 5490/zynq_axi_timer_led/zynq_axi_timer_led.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
# IP: The module: 'design_1_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Dell 5490/zynq_axi_timer_led/zynq_axi_timer_led.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/bd_afc3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Dell 5490/zynq_axi_timer_led/zynq_axi_timer_led.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/bd_afc3_sc_ul_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/Dell 5490/zynq_axi_timer_led/zynq_axi_timer_led.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/bd_afc3_sc_ul_0_cdc.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Dell 5490/zynq_axi_timer_led/zynq_axi_timer_led.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Dell 5490/zynq_axi_timer_led/zynq_axi_timer_led.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
